version: "3.9"
services:
  db:
    image: postgres:16
    container_name: aidev-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5435:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: aidev-redis
    ports:
      - "6379:6379"
volumes:
  dbdata:
