name: Deploy Workers

on:
  push:
    branches: [ main ]
    paths:
      - 'cloudflare/**'
      - '.github/workflows/deploy-workers.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup PNPM
        run: |
          npm i -g pnpm@9

      - name: Install and build (monorepo root)
        run: |
          pnpm install --frozen-lockfile || pnpm install
          pnpm build

      - name: Publish Worker (client dist as assets)
        working-directory: cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler@4 deploy --minify
